// Code generated by pdbgen from pdb.xml; DO NOT EDIT.
package model

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"
	"time"
)

// ErrConflict 表示Update时的旧值比对未命中：这一行在Load之后已经被其他请求改动过。
// 调用方应该重新Load最新数据、重跑业务逻辑后再Update一次，而不是把它当成普通错误直接抛给玩家。
var ErrUserConflict = errors.New("users: optimistic lock conflict, row changed since load")

// DBTX 兼容 *sql.DB 和 *sql.Tx，业务方按需传入其中之一
type DBTX interface {
	ExecContext(ctx context.Context, query string, args ...interface{}) (sql.Result, error)
	QueryRowContext(ctx context.Context, query string, args ...interface{}) *sql.Row
}

type User struct {
	Id          int64
	Name        string
	LastLoginAt time.Time
	CreatedAt   time.Time
	Token       string

	loaded          bool
	origName        string    // Load时的快照，Update做乐观锁比对用，业务代码不要读写
	origLastLoginAt time.Time // Load时的快照，Update做乐观锁比对用，业务代码不要读写
	origCreatedAt   time.Time // Load时的快照，Update做乐观锁比对用，业务代码不要读写
	origToken       string    // Load时的快照，Update做乐观锁比对用，业务代码不要读写
	dirty           map[string]bool
}

// NewUser 创建一个空对象，用于Insert前填充字段。
// 通过Load得到的对象不要用这个构造，Load内部会自己完成初始化。
func NewUser() *User {
	return &User{dirty: make(map[string]bool)}
}

// SetName 修改字段并标记为dirty，Update时只有dirty字段才会被写回
func (o *User) SetName(v string) {
	o.Name = v
	o.dirty["name"] = true
}

// SetLastLoginAt 修改字段并标记为dirty，Update时只有dirty字段才会被写回
func (o *User) SetLastLoginAt(v time.Time) {
	o.LastLoginAt = v
	o.dirty["last_login_at"] = true
}

// SetCreatedAt 修改字段并标记为dirty，Update时只有dirty字段才会被写回
func (o *User) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
	o.dirty["created_at"] = true
}

// SetToken 修改字段并标记为dirty，Update时只有dirty字段才会被写回
func (o *User) SetToken(v string) {
	o.Token = v
	o.dirty["token"] = true
}

const selectColumnsUser = "id, name, last_login_at, created_at, token"

func scanRowUser(row *sql.Row) (*User, error) {
	o := NewUser()
	if err := row.Scan(
		&o.Id,
		&o.Name,
		&o.LastLoginAt,
		&o.CreatedAt,
		&o.Token,
	); err != nil {
		return nil, err
	}
	o.loaded = true
	o.origName = o.Name
	o.origLastLoginAt = o.LastLoginAt
	o.origCreatedAt = o.CreatedAt
	o.origToken = o.Token
	o.dirty = make(map[string]bool)
	return o, nil
}

// LoadUser 按主键读取一行。
// 不加锁（不用 SELECT ... FOR UPDATE）——乐观锁模式下读不需要占用行锁，
// 读到写之间即使夹了耗时操作（比如调用AI接口），也不会占着DB连接。
func LoadUser(ctx context.Context, db DBTX, id int64) (*User, error) {
	const q = "SELECT " + selectColumnsUser + " FROM users WHERE id = $1"
	row := db.QueryRowContext(ctx, q, id)
	return scanRowUser(row)
}

// LoadUserByToken 按 (token) 索引读取一行
func LoadUserByToken(ctx context.Context, db DBTX, token string) (*User, error) {
	const q = "SELECT " + selectColumnsUser + " FROM users WHERE token = $1"
	row := db.QueryRowContext(ctx, q, token)
	return scanRowUser(row)
}

// LoadUserByIdToken 按 (id, token) 索引读取一行
func LoadUserByIdToken(ctx context.Context, db DBTX, id int64, token string) (*User, error) {
	const q = "SELECT " + selectColumnsUser + " FROM users WHERE id = $1 AND token = $2"
	row := db.QueryRowContext(ctx, q, id, token)
	return scanRowUser(row)
}

// Update 用字段级乐观锁把变化的字段写回，一次操作合并成一条SQL。
// 返回 ErrUserConflict 表示期间数据已被其他请求改动，调用方应重新Load后重试。
func (o *User) Update(ctx context.Context, tx DBTX) error {
	if !o.loaded {
		return errors.New("users: Update前必须先通过Load加载")
	}
	if len(o.dirty) == 0 {
		return nil
	}

	var sets []string
	var wheres []string
	var args []interface{}
	n := 0
	next := func() int { n++; return n }

	if o.dirty["name"] {
		sets = append(sets, fmt.Sprintf("name = $%d", next()))
		args = append(args, o.Name)
		wheres = append(wheres, fmt.Sprintf("name = $%d", next()))
		args = append(args, o.origName)
	}

	if o.dirty["last_login_at"] {
		sets = append(sets, fmt.Sprintf("last_login_at = $%d", next()))
		args = append(args, o.LastLoginAt)
		wheres = append(wheres, fmt.Sprintf("last_login_at = $%d", next()))
		args = append(args, o.origLastLoginAt)
	}

	if o.dirty["created_at"] {
		sets = append(sets, fmt.Sprintf("created_at = $%d", next()))
		args = append(args, o.CreatedAt)
		wheres = append(wheres, fmt.Sprintf("created_at = $%d", next()))
		args = append(args, o.origCreatedAt)
	}

	if o.dirty["token"] {
		sets = append(sets, fmt.Sprintf("token = $%d", next()))
		args = append(args, o.Token)
		wheres = append(wheres, fmt.Sprintf("token = $%d", next()))
		args = append(args, o.origToken)
	}

	args = append(args, o.Id)
	q := fmt.Sprintf("UPDATE users SET %s WHERE id = $%d AND %s",
		strings.Join(sets, ", "), n+1, strings.Join(wheres, " AND "))

	result, err := tx.ExecContext(ctx, q, args...)
	if err != nil {
		return err
	}
	affected, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if affected == 0 {
		return ErrUserConflict
	}

	o.origName = o.Name
	o.origLastLoginAt = o.LastLoginAt
	o.origCreatedAt = o.CreatedAt
	o.origToken = o.Token
	o.dirty = make(map[string]bool)
	return nil
}

// InsertUser 插入一行，主键由数据库自动生成并回填到返回对象。
func InsertUser(ctx context.Context, tx DBTX, name string, lastLoginAt time.Time, createdAt time.Time, token string) (*User, error) {
	const q = "INSERT INTO users (name, last_login_at, created_at, token) VALUES ($1, $2, $3, $4) RETURNING id"
	o := NewUser()
	o.Name = name
	o.LastLoginAt = lastLoginAt
	o.CreatedAt = createdAt
	o.Token = token
	row := tx.QueryRowContext(ctx, q, name, lastLoginAt, createdAt, token)
	if err := row.Scan(&o.Id); err != nil {
		return nil, err
	}
	o.loaded = true
	o.origName = o.Name
	o.origLastLoginAt = o.LastLoginAt
	o.origCreatedAt = o.CreatedAt
	o.origToken = o.Token
	o.dirty = make(map[string]bool)
	return o, nil
}
