// Code generated by pdbgen; DO NOT EDIT.
package ptable

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

type txKey struct{}
type querierKey struct{}

type DBTX interface {
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

type Querier interface {
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
}

func HasTx(ctx context.Context) bool {
	return ctx.Value(txKey{}) != nil
}

func txFromCtx(ctx context.Context) DBTX {
	return ctx.Value(txKey{}).(DBTX)
}

func txFromCtxOptional(ctx context.Context) (DBTX, bool) {
	res := ctx.Value(txKey{})
	if res == nil {
		return nil, false
	}

	return res.(DBTX), true
}

func querierFromCtx(ctx context.Context) Querier {
	if _, ok := txFromCtxOptional(ctx); ok {
		panic("SelectByXXX cannot be called inside transaction")
	}

	return ctx.Value(querierKey{}).(Querier)
}

func WithTx(ctx context.Context, tx DBTX) context.Context {
	return context.WithValue(ctx, txKey{}, tx)
}

func WithQuerier(ctx context.Context, q Querier) context.Context {
	return context.WithValue(ctx, querierKey{}, q)
}
