// Code generated by pdbgen; DO NOT EDIT.

package ptable

import (
	"context"
	"errors"
	"fmt"
	"math/bits"
	"strconv"
	"strings"

	"pdbgen/dbctx"
)

var UserTable user

type user struct{}

const (
	dirtyUserName        uint64 = 1 << 0
	dirtyUserLastLoginAt uint64 = 1 << 1
	dirtyUserCreatedAt   uint64 = 1 << 2
	dirtyUserToken       uint64 = 1 << 3
)

type User struct {
	id              int64
	name            string
	lastLoginAt     int64
	createdAt       int64
	token           string
	loaded          bool
	origName        string
	origLastLoginAt int64
	origCreatedAt   int64
	origToken       string
	dirty           uint64
}

func NewUser() *User {
	return &User{}
}

func loadedUser(
	id int64,
	name string,
	lastLoginAt int64,
	createdAt int64,
	token string,
) *User {
	return &User{
		id:              id,
		name:            name,
		lastLoginAt:     lastLoginAt,
		createdAt:       createdAt,
		token:           token,
		loaded:          true,
		origName:        name,
		origLastLoginAt: lastLoginAt,
		origCreatedAt:   createdAt,
		origToken:       token,
	}
}

func (o *User) Id() int64 {
	return o.id
}
func (o *User) SetName(v string) {
	if o.name == v {
		return
	}
	o.name = v
	o.dirty |= dirtyUserName
}

func (o *User) Name() string {
	return o.name
}
func (o *User) SetLastLoginAt(v int64) {
	if o.lastLoginAt == v {
		return
	}
	o.lastLoginAt = v
	o.dirty |= dirtyUserLastLoginAt
}

func (o *User) LastLoginAt() int64 {
	return o.lastLoginAt
}
func (o *User) SetCreatedAt(v int64) {
	if o.createdAt == v {
		return
	}
	o.createdAt = v
	o.dirty |= dirtyUserCreatedAt
}

func (o *User) CreatedAt() int64 {
	return o.createdAt
}
func (o *User) SetToken(v string) {
	if o.token == v {
		return
	}
	o.token = v
	o.dirty |= dirtyUserToken
}

func (o *User) Token() string {
	return o.token
}

func (o *User) ResetToLoaded() {
	o.name = o.origName
	o.lastLoginAt = o.origLastLoginAt
	o.createdAt = o.origCreatedAt
	o.token = o.origToken
	o.dirty = 0
}

const selectColumnsUser = "id, name, last_login_at, created_at, token"

func scanUser(s dbctx.Scanner) (*User, error) {
	var (
		id          int64
		name        string
		lastLoginAt int64
		createdAt   int64
		token       string
	)
	if err := s.Scan(
		&id,
		&name,
		&lastLoginAt,
		&createdAt,
		&token,
	); err != nil {
		return nil, err
	}
	return loadedUser(
		id,
		name,
		lastLoginAt,
		createdAt,
		token,
	), nil
}

func (o user) getId(
	ctx context.Context,
	q dbctx.Querier,
	id int64,
) *User {
	const query = "SELECT " + selectColumnsUser +
		" FROM user" +
		" WHERE id = $1"
	return dbctx.QueryOne(ctx, q, query, scanUser, id)
}

func (o user) GetById(
	ctx context.Context,
	id int64,
) *User {
	return o.getId(
		ctx,
		dbctx.TxFromCtx(ctx),
		id,
	)
}

func (o user) SelectById(
	ctx context.Context,
	id int64,
) *User {
	return o.getId(
		ctx,
		dbctx.QuerierFromCtx(ctx),
		id,
	)
}

func (o user) getAll(
	ctx context.Context,
	q dbctx.Querier,
) []*User {
	const query = "SELECT " + selectColumnsUser +
		" FROM user"
	return dbctx.QueryList(ctx, q, query, scanUser)
}

func (o user) GetAll(
	ctx context.Context,
) []*User {
	return o.getAll(ctx, dbctx.TxFromCtx(ctx))
}

func (o user) SelectAll(
	ctx context.Context,
) []*User {
	return o.getAll(ctx, dbctx.QuerierFromCtx(ctx))
}

var ErrUserNotFound = errors.New(
	"user: row not found at update time",
)

// FlushStmt 实现 dbctx.Flusher。dirty == 0 时返回空 query，
// UnitOfWork 据此跳过这一行，不占用一次往返。
func (v *User) FlushStmt() (string, []any) {
	if !v.loaded || v.dirty == 0 {
		return "", nil
	}
	var sb strings.Builder
	args := make([]any, 0, bits.OnesCount64(v.dirty)+1)
	sb.WriteString("UPDATE user SET ")
	if v.dirty&dirtyUserName != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.name)
		sb.WriteString("name = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyUserLastLoginAt != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.lastLoginAt)
		sb.WriteString("last_login_at = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyUserCreatedAt != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.createdAt)
		sb.WriteString("created_at = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyUserToken != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.token)
		sb.WriteString("token = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	args = append(args, v.id)
	sb.WriteString(" WHERE id = $")
	sb.WriteString(strconv.Itoa(len(args)))
	return sb.String(), args
}

// FlushDone 实现 dbctx.Flusher，在对应 UPDATE 执行成功后回调，
// 同步 orig 快照并清空 dirty；rows == 0 说明这一行已被删除或从未存在。
func (v *User) FlushDone(rows int64) error {
	if rows == 0 {
		return ErrUserNotFound
	}
	v.origName = v.name
	v.origLastLoginAt = v.lastLoginAt
	v.origCreatedAt = v.createdAt
	v.origToken = v.token
	v.dirty = 0
	return nil
}

// Update 是不经过 UnitOfWork 的直接落库入口，
// 生成代码内部不再调用它，仅供业务代码需要立即写库时使用。
func (o user) Update(
	ctx context.Context,
	v *User,
) error {
	query, args := v.FlushStmt()
	if query == "" {
		return nil
	}
	tag, err := dbctx.TxFromCtx(ctx).Exec(ctx, query, args...)
	if err != nil {
		return fmt.Errorf("user update: %w", err)
	}
	return v.FlushDone(tag.RowsAffected())
}

func (o user) Insert(
	ctx context.Context,
	v *User,
) {
	tx := dbctx.TxFromCtx(ctx)
	const query = "INSERT INTO user " +
		"(name, last_login_at, created_at, token) " +
		"VALUES ($1, $2, $3, $4)" +
		" RETURNING id"

	row := tx.QueryRow(
		ctx,
		query,
		v.name,
		v.lastLoginAt,
		v.createdAt,
		v.token,
	)
	if err := row.Scan(
		&v.id,
	); err != nil {
		panic(err)
	}

	v.loaded = true

	v.origName = v.name

	v.origLastLoginAt = v.lastLoginAt

	v.origCreatedAt = v.createdAt

	v.origToken = v.token

	v.dirty = 0
	dbctx.Track(ctx, v)
}
