// Code generated by pdbgen; DO NOT EDIT.

package ptable

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
)

var UserTable user

type user struct{}

type User struct {
	id          int64
	name        string
	lastLoginAt int64
	createdAt   int64
	token       string

	loaded          bool
	origName        string
	origLastLoginAt int64
	origCreatedAt   int64
	origToken       string

	dirty map[string]struct{}
}

func NewUser() *User {
	return &User{
		dirty: make(map[string]struct{}),
	}
}

func loadedUser(
	id int64,
	name string,
	lastLoginAt int64,
	createdAt int64,
	token string,
) *User {
	return &User{
		id:              id,
		name:            name,
		lastLoginAt:     lastLoginAt,
		createdAt:       createdAt,
		token:           token,
		loaded:          true,
		origName:        name,
		origLastLoginAt: lastLoginAt,
		origCreatedAt:   createdAt,
		origToken:       token,
		dirty:           make(map[string]struct{}),
	}
}

func (o *User) Id() int64 {
	return o.id
}

func (o *User) SetName(v string) {
	if o.name == v {
		return
	}

	o.name = v
	o.dirty["name"] = struct{}{}
}

func (o *User) Name() string {
	return o.name
}

func (o *User) SetLastLoginAt(v int64) {
	if o.lastLoginAt == v {
		return
	}

	o.lastLoginAt = v
	o.dirty["last_login_at"] = struct{}{}
}

func (o *User) LastLoginAt() int64 {
	return o.lastLoginAt
}

func (o *User) SetCreatedAt(v int64) {
	if o.createdAt == v {
		return
	}

	o.createdAt = v
	o.dirty["created_at"] = struct{}{}
}

func (o *User) CreatedAt() int64 {
	return o.createdAt
}

func (o *User) SetToken(v string) {
	if o.token == v {
		return
	}

	o.token = v
	o.dirty["token"] = struct{}{}
}

func (o *User) Token() string {
	return o.token
}

func (o *User) ResetToLoaded() {
	o.name = o.origName
	o.lastLoginAt = o.origLastLoginAt
	o.createdAt = o.origCreatedAt
	o.token = o.origToken

	o.dirty = make(map[string]struct{})
}

const selectColumnsUser = "id, name, last_login_at, created_at, token"

func scanUserRow(
	row pgx.Row,
) *User {
	var (
		id          int64
		name        string
		lastLoginAt int64
		createdAt   int64
		token       string
	)

	if err := row.Scan(
		&id,
		&name,
		&lastLoginAt,
		&createdAt,
		&token,
	); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil
		}

		panic(err)
	}

	return loadedUser(
		id,
		name,
		lastLoginAt,
		createdAt,
		token,
	)
}

func scanUserRows(
	rows pgx.Rows,
) *User {
	var (
		id          int64
		name        string
		lastLoginAt int64
		createdAt   int64
		token       string
	)

	if err := rows.Scan(
		&id,
		&name,
		&lastLoginAt,
		&createdAt,
		&token,
	); err != nil {
		panic(err)
	}

	return loadedUser(
		id,
		name,
		lastLoginAt,
		createdAt,
		token,
	)
}

func (o user) getId(
	ctx context.Context,
	q Querier,
	id int64,
) *User {
	const query = "SELECT " + selectColumnsUser +
		" FROM user" +
		" WHERE id = $1"

	row := q.QueryRow(
		ctx,
		query,
		id,
	)

	return scanUserRow(row)
}

func (o user) GetById(
	ctx context.Context,
	id int64,
) *User {
	return o.getId(
		ctx,
		txFromCtx(ctx),
		id,
	)
}

func (o user) SelectById(
	ctx context.Context,
	id int64,
) *User {
	return o.getId(
		ctx,
		querierFromCtx(ctx),
		id,
	)
}

func (o user) getAll(
	ctx context.Context,
	q Querier,
) []*User {
	const query = "SELECT " + selectColumnsUser +
		" FROM user"

	rows, err := q.Query(
		ctx,
		query,
	)
	if err != nil {
		panic(err)
	}
	defer rows.Close()

	var result []*User

	for rows.Next() {
		result = append(
			result,
			scanUserRows(rows),
		)
	}

	if err := rows.Err(); err != nil {
		panic(err)
	}

	return result
}

func (o user) GetAll(
	ctx context.Context,
) []*User {
	return o.getAll(
		ctx,
		txFromCtx(ctx),
	)
}

func (o user) SelectAll(
	ctx context.Context,
) []*User {
	return o.getAll(
		ctx,
		querierFromCtx(ctx),
	)
}

var ErrUserNotFound = errors.New(
	"user: row not found at update time",
)

func (o user) Update(
	ctx context.Context,
	v *User,
) error {
	tx := txFromCtx(ctx)

	if !v.loaded {
		return errors.New(
			"update User must load first",
		)
	}

	if len(v.dirty) == 0 {
		return nil
	}

	var sets []string
	var args []any

	n := 0

	next := func() int {
		n++
		return n
	}

	if _, ok := v.dirty["name"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"name = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.name,
		)
	}

	if _, ok := v.dirty["last_login_at"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"last_login_at = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.lastLoginAt,
		)
	}

	if _, ok := v.dirty["created_at"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"created_at = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.createdAt,
		)
	}

	if _, ok := v.dirty["token"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"token = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.token,
		)
	}

	args = append(
		args,
		v.id,
	)

	query := fmt.Sprintf(
		"UPDATE user SET %s WHERE id = $%d",
		strings.Join(sets, ", "),
		n+1,
	)

	tag, err := tx.Exec(
		ctx,
		query,
		args...,
	)
	if err != nil {
		panic(err)
	}

	if tag.RowsAffected() == 0 {
		return ErrUserNotFound
	}

	v.origName = v.name

	v.origLastLoginAt = v.lastLoginAt

	v.origCreatedAt = v.createdAt

	v.origToken = v.token

	v.dirty = make(map[string]struct{})

	return nil
}

func (o user) Insert(
	ctx context.Context,
	v *User,
) {
	tx := txFromCtx(ctx)

	const query = "INSERT INTO user " +
		"(name, last_login_at, created_at, token) " +
		"VALUES ($1, $2, $3, $4)" +
		" RETURNING id"

	row := tx.QueryRow(
		ctx,
		query,
		v.name,
		v.lastLoginAt,
		v.createdAt,
		v.token,
	)

	if err := row.Scan(
		&v.id,
	); err != nil {
		panic(err)
	}

	v.loaded = true

	v.origName = v.name

	v.origLastLoginAt = v.lastLoginAt

	v.origCreatedAt = v.createdAt

	v.origToken = v.token

	v.dirty = make(map[string]struct{})
}
