// Code generated by pdbgen; DO NOT EDIT.

package ptable

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
)

var UserRedEnvelopeTable redEnvelope

type redEnvelope struct{}

type RedEnvelope struct {
	id            int64
	uid           int64
	actId         int32
	lastRefreshAt int64
	todayCount    int32
	total         int32

	loaded            bool
	origUid           int64
	origActId         int32
	origLastRefreshAt int64
	origTodayCount    int32
	origTotal         int32

	dirty map[string]struct{}
}

func NewRedEnvelope() *RedEnvelope {
	return &RedEnvelope{
		dirty: make(map[string]struct{}),
	}
}

func loadedRedEnvelope(
	id int64,
	uid int64,
	actId int32,
	lastRefreshAt int64,
	todayCount int32,
	total int32,
) *RedEnvelope {
	return &RedEnvelope{
		id:            id,
		uid:           uid,
		actId:         actId,
		lastRefreshAt: lastRefreshAt,
		todayCount:    todayCount,
		total:         total,

		loaded:            true,
		origUid:           uid,
		origActId:         actId,
		origLastRefreshAt: lastRefreshAt,
		origTodayCount:    todayCount,
		origTotal:         total,

		dirty: make(map[string]struct{}),
	}
}

func (o *RedEnvelope) SetUid(v int64) {
	if o.uid == v {
		return
	}

	o.uid = v
	o.dirty["uid"] = struct{}{}
}

func (o *RedEnvelope) Uid() int64 {
	return o.uid
}

func (o *RedEnvelope) SetActId(v int32) {
	if o.actId == v {
		return
	}

	o.actId = v
	o.dirty["act_id"] = struct{}{}
}

func (o *RedEnvelope) ActId() int32 {
	return o.actId
}

func (o *RedEnvelope) SetLastRefreshAt(v int64) {
	if o.lastRefreshAt == v {
		return
	}

	o.lastRefreshAt = v
	o.dirty["last_refresh_at"] = struct{}{}
}

func (o *RedEnvelope) LastRefreshAt() int64 {
	return o.lastRefreshAt
}

func (o *RedEnvelope) SetTodayCount(v int32) {
	if o.todayCount == v {
		return
	}

	o.todayCount = v
	o.dirty["today_count"] = struct{}{}
}

func (o *RedEnvelope) TodayCount() int32 {
	return o.todayCount
}

func (o *RedEnvelope) SetTotal(v int32) {
	if o.total == v {
		return
	}

	o.total = v
	o.dirty["total"] = struct{}{}
}

func (o *RedEnvelope) Total() int32 {
	return o.total
}

func (o *RedEnvelope) Id() int64 {
	return o.id
}

// ResetToLoaded restores every non-primary-key field to the last
// successfully loaded/inserted/updated snapshot.
func (o *RedEnvelope) ResetToLoaded() {
	o.uid = o.origUid
	o.actId = o.origActId
	o.lastRefreshAt = o.origLastRefreshAt
	o.todayCount = o.origTodayCount
	o.total = o.origTotal

	o.dirty = make(map[string]struct{})
}

const selectColumnsRedEnvelope = "id, uid, act_id, last_refresh_at, today_count, total"

func scanRedEnvelope(row pgx.Row) *RedEnvelope {
	var (
		id            int64
		uid           int64
		actId         int32
		lastRefreshAt int64
		todayCount    int32
		total         int32
	)

	if err := row.Scan(
		&id,
		&uid,
		&actId,
		&lastRefreshAt,
		&todayCount,
		&total,
	); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil
		}

		panic(err)
	}

	return loadedRedEnvelope(
		id,
		uid,
		actId,
		lastRefreshAt,
		todayCount,
		total,
	)
}

func (redEnvelope) GetById(
	ctx context.Context,
	id int64,
) *RedEnvelope {
	tx := txFromCtx(ctx)

	const q = "SELECT " + selectColumnsRedEnvelope +
		" FROM user_red_envelope" +
		" WHERE id = $1"

	row := tx.QueryRow(
		ctx,
		q,
		id,
	)

	return scanRedEnvelope(row)
}

func (redEnvelope) GetByUidActId(
	ctx context.Context,
	uid int64, actId int32,
) *RedEnvelope {
	tx := txFromCtx(ctx)

	const q = "SELECT " + selectColumnsRedEnvelope +
		" FROM user_red_envelope" +
		" WHERE uid = $1 AND act_id = $2"

	row := tx.QueryRow(
		ctx,
		q,
		uid, actId,
	)

	return scanRedEnvelope(row)
}

func (redEnvelope) Update(
	ctx context.Context,
	o *RedEnvelope,
) error {
	tx := txFromCtx(ctx)

	if !o.loaded {
		return errors.New(
			"update RedEnvelope must load first",
		)
	}

	if len(o.dirty) == 0 {
		return nil
	}

	var sets []string
	var args []any

	n := 0

	next := func() int {
		n++
		return n
	}

	if _, ok := o.dirty["uid"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"uid = $%d",
				next(),
			),
		)

		args = append(
			args,
			o.uid,
		)
	}

	if _, ok := o.dirty["act_id"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"act_id = $%d",
				next(),
			),
		)

		args = append(
			args,
			o.actId,
		)
	}

	if _, ok := o.dirty["last_refresh_at"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"last_refresh_at = $%d",
				next(),
			),
		)

		args = append(
			args,
			o.lastRefreshAt,
		)
	}

	if _, ok := o.dirty["today_count"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"today_count = $%d",
				next(),
			),
		)

		args = append(
			args,
			o.todayCount,
		)
	}

	if _, ok := o.dirty["total"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"total = $%d",
				next(),
			),
		)

		args = append(
			args,
			o.total,
		)
	}

	args = append(args, o.id)

	q := fmt.Sprintf(
		"UPDATE user_red_envelope SET %s WHERE id = $%d",
		strings.Join(sets, ", "),
		n+1,
	)

	tag, err := tx.Exec(ctx, q, args...)
	if err != nil {
		panic(err)
	}

	if tag.RowsAffected() == 0 {
		return ErrRedEnvelopeNotFound
	}

	o.origUid = o.uid

	o.origActId = o.actId

	o.origLastRefreshAt = o.lastRefreshAt

	o.origTodayCount = o.todayCount

	o.origTotal = o.total

	o.dirty = make(map[string]struct{})

	return nil
}

var ErrRedEnvelopeNotFound = errors.New(
	"user_red_envelope: row not found at update time",
)

func (redEnvelope) Insert(
	ctx context.Context,
	o *RedEnvelope,
) {
	tx := txFromCtx(ctx)

	const q = "INSERT INTO user_red_envelope " +
		"(uid, act_id, last_refresh_at, today_count, total) " +
		"VALUES ($1, $2, $3, $4, $5)" +
		" RETURNING id"

	row := tx.QueryRow(
		ctx,
		q,
		o.uid,
		o.actId,
		o.lastRefreshAt,
		o.todayCount,
		o.total,
	)

	if err := row.Scan(&o.id); err != nil {
		panic(err)
	}

	o.loaded = true

	o.origUid = o.uid

	o.origActId = o.actId

	o.origLastRefreshAt = o.lastRefreshAt

	o.origTodayCount = o.todayCount

	o.origTotal = o.total

	o.dirty = make(map[string]struct{})
}
