// Code generated by pdbgen; DO NOT EDIT.

package ptable

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
)

var UserMailTable mail

type mail struct{}

type Mail struct {
	id        int64
	uid       int64
	confId    int32
	state     int32
	receiveAt int64
	params    string
	awardList string

	loaded        bool
	origUid       int64
	origConfId    int32
	origState     int32
	origReceiveAt int64
	origParams    string
	origAwardList string

	dirty map[string]struct{}
}

func NewMail() *Mail {
	return &Mail{
		dirty: make(map[string]struct{}),
	}
}

func loadedMail(
	id int64,
	uid int64,
	confId int32,
	state int32,
	receiveAt int64,
	params string,
	awardList string,
) *Mail {
	return &Mail{
		id:            id,
		uid:           uid,
		confId:        confId,
		state:         state,
		receiveAt:     receiveAt,
		params:        params,
		awardList:     awardList,
		loaded:        true,
		origUid:       uid,
		origConfId:    confId,
		origState:     state,
		origReceiveAt: receiveAt,
		origParams:    params,
		origAwardList: awardList,
		dirty:         make(map[string]struct{}),
	}
}

func (o *Mail) Id() int64 {
	return o.id
}

func (o *Mail) SetUid(v int64) {
	if o.uid == v {
		return
	}

	o.uid = v
	o.dirty["uid"] = struct{}{}
}

func (o *Mail) Uid() int64 {
	return o.uid
}

func (o *Mail) SetConfId(v int32) {
	if o.confId == v {
		return
	}

	o.confId = v
	o.dirty["conf_id"] = struct{}{}
}

func (o *Mail) ConfId() int32 {
	return o.confId
}

func (o *Mail) SetState(v int32) {
	if o.state == v {
		return
	}

	o.state = v
	o.dirty["state"] = struct{}{}
}

func (o *Mail) State() int32 {
	return o.state
}

func (o *Mail) SetReceiveAt(v int64) {
	if o.receiveAt == v {
		return
	}

	o.receiveAt = v
	o.dirty["receive_at"] = struct{}{}
}

func (o *Mail) ReceiveAt() int64 {
	return o.receiveAt
}

func (o *Mail) SetParams(v string) {
	if o.params == v {
		return
	}

	o.params = v
	o.dirty["params"] = struct{}{}
}

func (o *Mail) Params() string {
	return o.params
}

func (o *Mail) SetAwardList(v string) {
	if o.awardList == v {
		return
	}

	o.awardList = v
	o.dirty["award_list"] = struct{}{}
}

func (o *Mail) AwardList() string {
	return o.awardList
}

func (o *Mail) ResetToLoaded() {
	o.uid = o.origUid
	o.confId = o.origConfId
	o.state = o.origState
	o.receiveAt = o.origReceiveAt
	o.params = o.origParams
	o.awardList = o.origAwardList

	o.dirty = make(map[string]struct{})
}

const selectColumnsMail = "id, uid, conf_id, state, receive_at, params, award_list"

func scanMailRow(
	row pgx.Row,
) *Mail {
	var (
		id        int64
		uid       int64
		confId    int32
		state     int32
		receiveAt int64
		params    string
		awardList string
	)

	if err := row.Scan(
		&id,
		&uid,
		&confId,
		&state,
		&receiveAt,
		&params,
		&awardList,
	); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil
		}

		panic(err)
	}

	return loadedMail(
		id,
		uid,
		confId,
		state,
		receiveAt,
		params,
		awardList,
	)
}

func scanMailRows(
	rows pgx.Rows,
) *Mail {
	var (
		id        int64
		uid       int64
		confId    int32
		state     int32
		receiveAt int64
		params    string
		awardList string
	)

	if err := rows.Scan(
		&id,
		&uid,
		&confId,
		&state,
		&receiveAt,
		&params,
		&awardList,
	); err != nil {
		panic(err)
	}

	return loadedMail(
		id,
		uid,
		confId,
		state,
		receiveAt,
		params,
		awardList,
	)
}

func (o mail) getId(
	ctx context.Context,
	q Querier,
	id int64,
) *Mail {
	const query = "SELECT " + selectColumnsMail +
		" FROM user_mail" +
		" WHERE id = $1"

	row := q.QueryRow(
		ctx,
		query,
		id,
	)

	return scanMailRow(row)
}

func (o mail) GetById(
	ctx context.Context,
	id int64,
) *Mail {
	return o.getId(
		ctx,
		txFromCtx(ctx),
		id,
	)
}

func (o mail) SelectById(
	ctx context.Context,
	id int64,
) *Mail {
	return o.getId(
		ctx,
		querierFromCtx(ctx),
		id,
	)
}

func (o mail) listUidConfId(
	ctx context.Context,
	q Querier,
	uid int64, confId int32,
) []*Mail {
	const query = "SELECT " + selectColumnsMail +
		" FROM user_mail" +
		" WHERE uid = $1 AND conf_id = $2"

	rows, err := q.Query(
		ctx,
		query,
		uid, confId,
	)
	if err != nil {
		panic(err)
	}
	defer rows.Close()

	var result []*Mail

	for rows.Next() {
		result = append(
			result,
			scanMailRows(rows),
		)
	}

	if err := rows.Err(); err != nil {
		panic(err)
	}

	return result
}

func (o mail) ListByUidConfId(
	ctx context.Context,
	uid int64, confId int32,
) []*Mail {
	return o.listUidConfId(
		ctx,
		txFromCtx(ctx),
		uid, confId,
	)
}

func (o mail) SelectListByUidConfId(
	ctx context.Context,
	uid int64, confId int32,
) []*Mail {
	return o.listUidConfId(
		ctx,
		querierFromCtx(ctx),
		uid, confId,
	)
}

func (o mail) getAll(
	ctx context.Context,
	q Querier,
) []*Mail {
	const query = "SELECT " + selectColumnsMail +
		" FROM user_mail"

	rows, err := q.Query(
		ctx,
		query,
	)
	if err != nil {
		panic(err)
	}
	defer rows.Close()

	var result []*Mail

	for rows.Next() {
		result = append(
			result,
			scanMailRows(rows),
		)
	}

	if err := rows.Err(); err != nil {
		panic(err)
	}

	return result
}

func (o mail) GetAll(
	ctx context.Context,
) []*Mail {
	return o.getAll(
		ctx,
		txFromCtx(ctx),
	)
}

func (o mail) SelectAll(
	ctx context.Context,
) []*Mail {
	return o.getAll(
		ctx,
		querierFromCtx(ctx),
	)
}

var ErrMailNotFound = errors.New(
	"user_mail: row not found at update time",
)

func (o mail) Update(
	ctx context.Context,
	v *Mail,
) error {
	tx := txFromCtx(ctx)

	if !v.loaded {
		return errors.New(
			"update Mail must load first",
		)
	}

	if len(v.dirty) == 0 {
		return nil
	}

	var sets []string
	var args []any

	n := 0

	next := func() int {
		n++
		return n
	}

	if _, ok := v.dirty["uid"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"uid = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.uid,
		)
	}

	if _, ok := v.dirty["conf_id"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"conf_id = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.confId,
		)
	}

	if _, ok := v.dirty["state"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"state = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.state,
		)
	}

	if _, ok := v.dirty["receive_at"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"receive_at = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.receiveAt,
		)
	}

	if _, ok := v.dirty["params"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"params = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.params,
		)
	}

	if _, ok := v.dirty["award_list"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"award_list = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.awardList,
		)
	}

	args = append(
		args,
		v.id,
	)

	query := fmt.Sprintf(
		"UPDATE user_mail SET %s WHERE id = $%d",
		strings.Join(sets, ", "),
		n+1,
	)

	tag, err := tx.Exec(
		ctx,
		query,
		args...,
	)
	if err != nil {
		panic(err)
	}

	if tag.RowsAffected() == 0 {
		return ErrMailNotFound
	}

	v.origUid = v.uid

	v.origConfId = v.confId

	v.origState = v.state

	v.origReceiveAt = v.receiveAt

	v.origParams = v.params

	v.origAwardList = v.awardList

	v.dirty = make(map[string]struct{})

	return nil
}

func (o mail) Insert(
	ctx context.Context,
	v *Mail,
) {
	tx := txFromCtx(ctx)

	const query = "INSERT INTO user_mail " +
		"(uid, conf_id, state, receive_at, params, award_list) " +
		"VALUES ($1, $2, $3, $4, $5, $6)" +
		" RETURNING id"

	row := tx.QueryRow(
		ctx,
		query,
		v.uid,
		v.confId,
		v.state,
		v.receiveAt,
		v.params,
		v.awardList,
	)

	if err := row.Scan(
		&v.id,
	); err != nil {
		panic(err)
	}

	v.loaded = true

	v.origUid = v.uid

	v.origConfId = v.confId

	v.origState = v.state

	v.origReceiveAt = v.receiveAt

	v.origParams = v.params

	v.origAwardList = v.awardList

	v.dirty = make(map[string]struct{})
}
