// Code generated by pdbgen; DO NOT EDIT.

package ptable

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
)

var UserRedEnvelopeTable redEnvelope

type redEnvelope struct{}

type RedEnvelope struct {
	id            int64
	uid           int64
	actId         int32
	lastRefreshAt int64
	todayCount    int32
	total         int32

	loaded            bool
	origUid           int64
	origActId         int32
	origLastRefreshAt int64
	origTodayCount    int32
	origTotal         int32

	dirty map[string]struct{}
}

func NewRedEnvelope() *RedEnvelope {
	return &RedEnvelope{
		dirty: make(map[string]struct{}),
	}
}

func loadedRedEnvelope(
	id int64,
	uid int64,
	actId int32,
	lastRefreshAt int64,
	todayCount int32,
	total int32,
) *RedEnvelope {
	return &RedEnvelope{
		id:                id,
		uid:               uid,
		actId:             actId,
		lastRefreshAt:     lastRefreshAt,
		todayCount:        todayCount,
		total:             total,
		loaded:            true,
		origUid:           uid,
		origActId:         actId,
		origLastRefreshAt: lastRefreshAt,
		origTodayCount:    todayCount,
		origTotal:         total,
		dirty:             make(map[string]struct{}),
	}
}

func (o *RedEnvelope) Id() int64 {
	return o.id
}

func (o *RedEnvelope) SetUid(v int64) {
	if o.uid == v {
		return
	}

	o.uid = v
	o.dirty["uid"] = struct{}{}
}

func (o *RedEnvelope) Uid() int64 {
	return o.uid
}

func (o *RedEnvelope) SetActId(v int32) {
	if o.actId == v {
		return
	}

	o.actId = v
	o.dirty["act_id"] = struct{}{}
}

func (o *RedEnvelope) ActId() int32 {
	return o.actId
}

func (o *RedEnvelope) SetLastRefreshAt(v int64) {
	if o.lastRefreshAt == v {
		return
	}

	o.lastRefreshAt = v
	o.dirty["last_refresh_at"] = struct{}{}
}

func (o *RedEnvelope) LastRefreshAt() int64 {
	return o.lastRefreshAt
}

func (o *RedEnvelope) SetTodayCount(v int32) {
	if o.todayCount == v {
		return
	}

	o.todayCount = v
	o.dirty["today_count"] = struct{}{}
}

func (o *RedEnvelope) TodayCount() int32 {
	return o.todayCount
}

func (o *RedEnvelope) SetTotal(v int32) {
	if o.total == v {
		return
	}

	o.total = v
	o.dirty["total"] = struct{}{}
}

func (o *RedEnvelope) Total() int32 {
	return o.total
}

func (o *RedEnvelope) ResetToLoaded() {
	o.uid = o.origUid
	o.actId = o.origActId
	o.lastRefreshAt = o.origLastRefreshAt
	o.todayCount = o.origTodayCount
	o.total = o.origTotal

	o.dirty = make(map[string]struct{})
}

const selectColumnsRedEnvelope = "id, uid, act_id, last_refresh_at, today_count, total"

func scanRedEnvelopeRow(
	row pgx.Row,
) *RedEnvelope {
	var (
		id            int64
		uid           int64
		actId         int32
		lastRefreshAt int64
		todayCount    int32
		total         int32
	)

	if err := row.Scan(
		&id,
		&uid,
		&actId,
		&lastRefreshAt,
		&todayCount,
		&total,
	); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil
		}

		panic(err)
	}

	return loadedRedEnvelope(
		id,
		uid,
		actId,
		lastRefreshAt,
		todayCount,
		total,
	)
}

func scanRedEnvelopeRows(
	rows pgx.Rows,
) *RedEnvelope {
	var (
		id            int64
		uid           int64
		actId         int32
		lastRefreshAt int64
		todayCount    int32
		total         int32
	)

	if err := rows.Scan(
		&id,
		&uid,
		&actId,
		&lastRefreshAt,
		&todayCount,
		&total,
	); err != nil {
		panic(err)
	}

	return loadedRedEnvelope(
		id,
		uid,
		actId,
		lastRefreshAt,
		todayCount,
		total,
	)
}

func (o redEnvelope) getId(
	ctx context.Context,
	q Querier,
	registerUpdate bool,
	id int64,
) *RedEnvelope {
	const query = "SELECT " + selectColumnsRedEnvelope +
		" FROM user_red_envelope" +
		" WHERE id = $1"

	row := q.QueryRow(
		ctx,
		query,
		id,
	)

	obj := scanRedEnvelopeRow(row)
	if obj == nil {
		return nil
	}
	if registerUpdate {
		registerDirtyObject(
			ctx,
			obj,
			func(ctx context.Context) error {
				return o.Update(ctx, obj)
			},
		)
	}

	return obj
}

func (o redEnvelope) GetById(
	ctx context.Context,
	id int64,
) *RedEnvelope {
	return o.getId(
		ctx,
		txFromCtx(ctx),
		true,
		id,
	)
}

func (o redEnvelope) SelectById(
	ctx context.Context,
	id int64,
) *RedEnvelope {
	return o.getId(
		ctx,
		querierFromCtx(ctx),
		false,
		id,
	)
}

func (o redEnvelope) getUidActId(
	ctx context.Context,
	q Querier,
	registerUpdate bool,
	uid int64, actId int32,
) *RedEnvelope {
	const query = "SELECT " + selectColumnsRedEnvelope +
		" FROM user_red_envelope" +
		" WHERE uid = $1 AND act_id = $2"

	row := q.QueryRow(
		ctx,
		query,
		uid, actId,
	)

	obj := scanRedEnvelopeRow(row)
	if obj == nil {
		return nil
	}
	if registerUpdate {
		registerDirtyObject(
			ctx,
			obj,
			func(ctx context.Context) error {
				return o.Update(ctx, obj)
			},
		)
	}

	return obj
}

func (o redEnvelope) GetByUidActId(
	ctx context.Context,
	uid int64, actId int32,
) *RedEnvelope {
	return o.getUidActId(
		ctx,
		txFromCtx(ctx),
		true,
		uid, actId,
	)
}

func (o redEnvelope) SelectByUidActId(
	ctx context.Context,
	uid int64, actId int32,
) *RedEnvelope {
	return o.getUidActId(
		ctx,
		querierFromCtx(ctx),
		false,
		uid, actId,
	)
}

func (o redEnvelope) getAll(
	ctx context.Context,
	q Querier,
	registerUpdate bool,
) []*RedEnvelope {
	const query = "SELECT " + selectColumnsRedEnvelope +
		" FROM user_red_envelope"

	rows, err := q.Query(
		ctx,
		query,
	)
	if err != nil {
		panic(err)
	}
	defer rows.Close()

	var result []*RedEnvelope

	for rows.Next() {
		obj := scanRedEnvelopeRows(rows)
		if registerUpdate {
			registerDirtyObject(
				ctx,
				obj,
				func(ctx context.Context) error {
					return o.Update(ctx, obj)
				},
			)
		}
		result = append(
			result,
			obj,
		)
	}

	if err := rows.Err(); err != nil {
		panic(err)
	}

	return result
}

func (o redEnvelope) GetAll(
	ctx context.Context,
) []*RedEnvelope {
	return o.getAll(
		ctx,
		txFromCtx(ctx),
		true,
	)
}

func (o redEnvelope) SelectAll(
	ctx context.Context,
) []*RedEnvelope {
	return o.getAll(
		ctx,
		querierFromCtx(ctx),
		false,
	)
}

var ErrRedEnvelopeNotFound = errors.New(
	"user_red_envelope: row not found at update time",
)

func (o redEnvelope) Update(
	ctx context.Context,
	v *RedEnvelope,
) error {
	tx := txFromCtx(ctx)

	if !v.loaded {
		return errors.New(
			"update RedEnvelope must load first",
		)
	}

	if len(v.dirty) == 0 {
		return nil
	}

	var sets []string
	var args []any

	n := 0

	next := func() int {
		n++
		return n
	}

	if _, ok := v.dirty["uid"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"uid = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.uid,
		)
	}

	if _, ok := v.dirty["act_id"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"act_id = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.actId,
		)
	}

	if _, ok := v.dirty["last_refresh_at"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"last_refresh_at = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.lastRefreshAt,
		)
	}

	if _, ok := v.dirty["today_count"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"today_count = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.todayCount,
		)
	}

	if _, ok := v.dirty["total"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"total = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.total,
		)
	}

	args = append(
		args,
		v.id,
	)

	query := fmt.Sprintf(
		"UPDATE user_red_envelope SET %s WHERE id = $%d",
		strings.Join(sets, ", "),
		n+1,
	)

	tag, err := tx.Exec(
		ctx,
		query,
		args...,
	)
	if err != nil {
		panic(err)
	}

	if tag.RowsAffected() == 0 {
		return ErrRedEnvelopeNotFound
	}

	v.origUid = v.uid

	v.origActId = v.actId

	v.origLastRefreshAt = v.lastRefreshAt

	v.origTodayCount = v.todayCount

	v.origTotal = v.total

	v.dirty = make(map[string]struct{})

	return nil
}

func (o redEnvelope) Insert(
	ctx context.Context,
	v *RedEnvelope,
) {
	tx := txFromCtx(ctx)

	const query = "INSERT INTO user_red_envelope " +
		"(uid, act_id, last_refresh_at, today_count, total) " +
		"VALUES ($1, $2, $3, $4, $5)" +
		" RETURNING id"

	row := tx.QueryRow(
		ctx,
		query,
		v.uid,
		v.actId,
		v.lastRefreshAt,
		v.todayCount,
		v.total,
	)

	if err := row.Scan(
		&v.id,
	); err != nil {
		panic(err)
	}

	v.loaded = true

	v.origUid = v.uid

	v.origActId = v.actId

	v.origLastRefreshAt = v.lastRefreshAt

	v.origTodayCount = v.todayCount

	v.origTotal = v.total

	v.dirty = make(map[string]struct{})

	registerDirtyObject(
		ctx,
		v,
		func(ctx context.Context) error {
			return o.Update(ctx, v)
		},
	)
}
