// Code generated by pdbgen; DO NOT EDIT.

package ptable

import (
	"context"
	"errors"
	"fmt"
	"math/bits"
	"strconv"
	"strings"

	"pdbgen/dbctx"
)

var UserRedEnvelopeTable redEnvelope

type redEnvelope struct{}

const (
	dirtyRedEnvelopeUid           uint64 = 1 << 0
	dirtyRedEnvelopeActId         uint64 = 1 << 1
	dirtyRedEnvelopeLastRefreshAt uint64 = 1 << 2
	dirtyRedEnvelopeTodayCount    uint64 = 1 << 3
	dirtyRedEnvelopeTotal         uint64 = 1 << 4
)

type RedEnvelope struct {
	id                int64
	uid               int64
	actId             int32
	lastRefreshAt     int64
	todayCount        int32
	total             int32
	loaded            bool
	origUid           int64
	origActId         int32
	origLastRefreshAt int64
	origTodayCount    int32
	origTotal         int32
	dirty             uint64
}

func NewRedEnvelope() *RedEnvelope {
	return &RedEnvelope{}
}

func loadedRedEnvelope(
	id int64,
	uid int64,
	actId int32,
	lastRefreshAt int64,
	todayCount int32,
	total int32,
) *RedEnvelope {
	return &RedEnvelope{
		id:                id,
		uid:               uid,
		actId:             actId,
		lastRefreshAt:     lastRefreshAt,
		todayCount:        todayCount,
		total:             total,
		loaded:            true,
		origUid:           uid,
		origActId:         actId,
		origLastRefreshAt: lastRefreshAt,
		origTodayCount:    todayCount,
		origTotal:         total,
	}
}

func (o *RedEnvelope) Id() int64 {
	return o.id
}
func (o *RedEnvelope) SetUid(v int64) {
	if o.uid == v {
		return
	}
	o.uid = v
	o.dirty |= dirtyRedEnvelopeUid
}

func (o *RedEnvelope) Uid() int64 {
	return o.uid
}
func (o *RedEnvelope) SetActId(v int32) {
	if o.actId == v {
		return
	}
	o.actId = v
	o.dirty |= dirtyRedEnvelopeActId
}

func (o *RedEnvelope) ActId() int32 {
	return o.actId
}
func (o *RedEnvelope) SetLastRefreshAt(v int64) {
	if o.lastRefreshAt == v {
		return
	}
	o.lastRefreshAt = v
	o.dirty |= dirtyRedEnvelopeLastRefreshAt
}

func (o *RedEnvelope) LastRefreshAt() int64 {
	return o.lastRefreshAt
}
func (o *RedEnvelope) SetTodayCount(v int32) {
	if o.todayCount == v {
		return
	}
	o.todayCount = v
	o.dirty |= dirtyRedEnvelopeTodayCount
}

func (o *RedEnvelope) TodayCount() int32 {
	return o.todayCount
}
func (o *RedEnvelope) SetTotal(v int32) {
	if o.total == v {
		return
	}
	o.total = v
	o.dirty |= dirtyRedEnvelopeTotal
}

func (o *RedEnvelope) Total() int32 {
	return o.total
}

func (o *RedEnvelope) ResetToLoaded() {
	o.uid = o.origUid
	o.actId = o.origActId
	o.lastRefreshAt = o.origLastRefreshAt
	o.todayCount = o.origTodayCount
	o.total = o.origTotal
	o.dirty = 0
}

const selectColumnsRedEnvelope = "id, uid, act_id, last_refresh_at, today_count, total"

func scanRedEnvelope(s dbctx.Scanner) (*RedEnvelope, error) {
	var (
		id            int64
		uid           int64
		actId         int32
		lastRefreshAt int64
		todayCount    int32
		total         int32
	)
	if err := s.Scan(
		&id,
		&uid,
		&actId,
		&lastRefreshAt,
		&todayCount,
		&total,
	); err != nil {
		return nil, err
	}
	return loadedRedEnvelope(
		id,
		uid,
		actId,
		lastRefreshAt,
		todayCount,
		total,
	), nil
}

func (o redEnvelope) getId(
	ctx context.Context,
	q dbctx.Querier,
	id int64,
) *RedEnvelope {
	const query = "SELECT " + selectColumnsRedEnvelope +
		" FROM user_red_envelope" +
		" WHERE id = $1"
	return dbctx.QueryOne(ctx, q, query, scanRedEnvelope, id)
}

func (o redEnvelope) GetById(
	ctx context.Context,
	id int64,
) *RedEnvelope {
	return o.getId(
		ctx,
		dbctx.TxFromCtx(ctx),
		id,
	)
}

func (o redEnvelope) SelectById(
	ctx context.Context,
	id int64,
) *RedEnvelope {
	return o.getId(
		ctx,
		dbctx.QuerierFromCtx(ctx),
		id,
	)
}

func (o redEnvelope) getUidActId(
	ctx context.Context,
	q dbctx.Querier,
	uid int64, actId int32,
) *RedEnvelope {
	const query = "SELECT " + selectColumnsRedEnvelope +
		" FROM user_red_envelope" +
		" WHERE uid = $1 AND act_id = $2"
	return dbctx.QueryOne(ctx, q, query, scanRedEnvelope, uid, actId)
}

func (o redEnvelope) GetByUidActId(
	ctx context.Context,
	uid int64, actId int32,
) *RedEnvelope {
	return o.getUidActId(
		ctx,
		dbctx.TxFromCtx(ctx),
		uid, actId,
	)
}

func (o redEnvelope) SelectByUidActId(
	ctx context.Context,
	uid int64, actId int32,
) *RedEnvelope {
	return o.getUidActId(
		ctx,
		dbctx.QuerierFromCtx(ctx),
		uid, actId,
	)
}

func (o redEnvelope) getAll(
	ctx context.Context,
	q dbctx.Querier,
) []*RedEnvelope {
	const query = "SELECT " + selectColumnsRedEnvelope +
		" FROM user_red_envelope"
	return dbctx.QueryList(ctx, q, query, scanRedEnvelope)
}

func (o redEnvelope) GetAll(
	ctx context.Context,
) []*RedEnvelope {
	return o.getAll(ctx, dbctx.TxFromCtx(ctx))
}

func (o redEnvelope) SelectAll(
	ctx context.Context,
) []*RedEnvelope {
	return o.getAll(ctx, dbctx.QuerierFromCtx(ctx))
}

var ErrRedEnvelopeNotFound = errors.New(
	"user_red_envelope: row not found at update time",
)

// FlushStmt 实现 dbctx.Flusher。dirty == 0 时返回空 query，
// UnitOfWork 据此跳过这一行，不占用一次往返。
func (v *RedEnvelope) FlushStmt() (string, []any) {
	if !v.loaded || v.dirty == 0 {
		return "", nil
	}
	var sb strings.Builder
	args := make([]any, 0, bits.OnesCount64(v.dirty)+1)
	sb.WriteString("UPDATE user_red_envelope SET ")
	if v.dirty&dirtyRedEnvelopeUid != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.uid)
		sb.WriteString("uid = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyRedEnvelopeActId != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.actId)
		sb.WriteString("act_id = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyRedEnvelopeLastRefreshAt != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.lastRefreshAt)
		sb.WriteString("last_refresh_at = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyRedEnvelopeTodayCount != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.todayCount)
		sb.WriteString("today_count = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyRedEnvelopeTotal != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.total)
		sb.WriteString("total = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	args = append(args, v.id)
	sb.WriteString(" WHERE id = $")
	sb.WriteString(strconv.Itoa(len(args)))
	return sb.String(), args
}

// FlushDone 实现 dbctx.Flusher，在对应 UPDATE 执行成功后回调，
// 同步 orig 快照并清空 dirty；rows == 0 说明这一行已被删除或从未存在。
func (v *RedEnvelope) FlushDone(rows int64) error {
	if rows == 0 {
		return ErrRedEnvelopeNotFound
	}
	v.origUid = v.uid
	v.origActId = v.actId
	v.origLastRefreshAt = v.lastRefreshAt
	v.origTodayCount = v.todayCount
	v.origTotal = v.total
	v.dirty = 0
	return nil
}

// Update 是不经过 UnitOfWork 的直接落库入口，
// 生成代码内部不再调用它，仅供业务代码需要立即写库时使用。
func (o redEnvelope) Update(
	ctx context.Context,
	v *RedEnvelope,
) error {
	query, args := v.FlushStmt()
	if query == "" {
		return nil
	}
	tag, err := dbctx.TxFromCtx(ctx).Exec(ctx, query, args...)
	if err != nil {
		return fmt.Errorf("user_red_envelope update: %w", err)
	}
	return v.FlushDone(tag.RowsAffected())
}

func (o redEnvelope) Insert(
	ctx context.Context,
	v *RedEnvelope,
) {
	tx := dbctx.TxFromCtx(ctx)
	const query = "INSERT INTO user_red_envelope " +
		"(uid, act_id, last_refresh_at, today_count, total) " +
		"VALUES ($1, $2, $3, $4, $5)" +
		" RETURNING id"

	row := tx.QueryRow(
		ctx,
		query,
		v.uid,
		v.actId,
		v.lastRefreshAt,
		v.todayCount,
		v.total,
	)
	if err := row.Scan(
		&v.id,
	); err != nil {
		panic(err)
	}

	v.loaded = true

	v.origUid = v.uid

	v.origActId = v.actId

	v.origLastRefreshAt = v.lastRefreshAt

	v.origTodayCount = v.todayCount

	v.origTotal = v.total

	v.dirty = 0
	dbctx.Track(ctx, v)
}
