// Code generated by pdbgen; DO NOT EDIT.

package ptable

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
)

var UserGmMailTable gMMail

type gMMail struct{}

type GMMail struct {
	id            int64
	params        string
	awardList     string
	startAt       int64
	endAt         int64
	channel       string
	userCreatedAt int64
	condition     string

	loaded            bool
	origParams        string
	origAwardList     string
	origStartAt       int64
	origEndAt         int64
	origChannel       string
	origUserCreatedAt int64
	origCondition     string

	dirty map[string]struct{}
}

func NewGMMail() *GMMail {
	return &GMMail{
		dirty: make(map[string]struct{}),
	}
}

func loadedGMMail(
	id int64,
	params string,
	awardList string,
	startAt int64,
	endAt int64,
	channel string,
	userCreatedAt int64,
	condition string,
) *GMMail {
	return &GMMail{
		id:                id,
		params:            params,
		awardList:         awardList,
		startAt:           startAt,
		endAt:             endAt,
		channel:           channel,
		userCreatedAt:     userCreatedAt,
		condition:         condition,
		loaded:            true,
		origParams:        params,
		origAwardList:     awardList,
		origStartAt:       startAt,
		origEndAt:         endAt,
		origChannel:       channel,
		origUserCreatedAt: userCreatedAt,
		origCondition:     condition,
		dirty:             make(map[string]struct{}),
	}
}

func (o *GMMail) Id() int64 {
	return o.id
}

func (o *GMMail) SetParams(v string) {
	if o.params == v {
		return
	}

	o.params = v
	o.dirty["params"] = struct{}{}
}

func (o *GMMail) Params() string {
	return o.params
}

func (o *GMMail) SetAwardList(v string) {
	if o.awardList == v {
		return
	}

	o.awardList = v
	o.dirty["award_list"] = struct{}{}
}

func (o *GMMail) AwardList() string {
	return o.awardList
}

func (o *GMMail) SetStartAt(v int64) {
	if o.startAt == v {
		return
	}

	o.startAt = v
	o.dirty["start_at"] = struct{}{}
}

func (o *GMMail) StartAt() int64 {
	return o.startAt
}

func (o *GMMail) SetEndAt(v int64) {
	if o.endAt == v {
		return
	}

	o.endAt = v
	o.dirty["end_at"] = struct{}{}
}

func (o *GMMail) EndAt() int64 {
	return o.endAt
}

func (o *GMMail) SetChannel(v string) {
	if o.channel == v {
		return
	}

	o.channel = v
	o.dirty["channel"] = struct{}{}
}

func (o *GMMail) Channel() string {
	return o.channel
}

func (o *GMMail) SetUserCreatedAt(v int64) {
	if o.userCreatedAt == v {
		return
	}

	o.userCreatedAt = v
	o.dirty["user_created_at"] = struct{}{}
}

func (o *GMMail) UserCreatedAt() int64 {
	return o.userCreatedAt
}

func (o *GMMail) SetCondition(v string) {
	if o.condition == v {
		return
	}

	o.condition = v
	o.dirty["condition"] = struct{}{}
}

func (o *GMMail) Condition() string {
	return o.condition
}

func (o *GMMail) ResetToLoaded() {
	o.params = o.origParams
	o.awardList = o.origAwardList
	o.startAt = o.origStartAt
	o.endAt = o.origEndAt
	o.channel = o.origChannel
	o.userCreatedAt = o.origUserCreatedAt
	o.condition = o.origCondition

	o.dirty = make(map[string]struct{})
}

const selectColumnsGMMail = "id, params, award_list, start_at, end_at, channel, user_created_at, condition"

func scanGMMailRow(
	row pgx.Row,
) *GMMail {
	var (
		id            int64
		params        string
		awardList     string
		startAt       int64
		endAt         int64
		channel       string
		userCreatedAt int64
		condition     string
	)

	if err := row.Scan(
		&id,
		&params,
		&awardList,
		&startAt,
		&endAt,
		&channel,
		&userCreatedAt,
		&condition,
	); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil
		}

		panic(err)
	}

	return loadedGMMail(
		id,
		params,
		awardList,
		startAt,
		endAt,
		channel,
		userCreatedAt,
		condition,
	)
}

func scanGMMailRows(
	rows pgx.Rows,
) *GMMail {
	var (
		id            int64
		params        string
		awardList     string
		startAt       int64
		endAt         int64
		channel       string
		userCreatedAt int64
		condition     string
	)

	if err := rows.Scan(
		&id,
		&params,
		&awardList,
		&startAt,
		&endAt,
		&channel,
		&userCreatedAt,
		&condition,
	); err != nil {
		panic(err)
	}

	return loadedGMMail(
		id,
		params,
		awardList,
		startAt,
		endAt,
		channel,
		userCreatedAt,
		condition,
	)
}

func (o gMMail) getId(
	ctx context.Context,
	q Querier,
	id int64,
) *GMMail {
	const query = "SELECT " + selectColumnsGMMail +
		" FROM user_gm_mail" +
		" WHERE id = $1"

	row := q.QueryRow(
		ctx,
		query,
		id,
	)

	return scanGMMailRow(row)
}

func (o gMMail) GetById(
	ctx context.Context,
	id int64,
) *GMMail {
	return o.getId(
		ctx,
		txFromCtx(ctx),
		id,
	)
}

func (o gMMail) SelectById(
	ctx context.Context,
	id int64,
) *GMMail {
	return o.getId(
		ctx,
		querierFromCtx(ctx),
		id,
	)
}

func (o gMMail) getAll(
	ctx context.Context,
	q Querier,
) []*GMMail {
	const query = "SELECT " + selectColumnsGMMail +
		" FROM user_gm_mail"

	rows, err := q.Query(
		ctx,
		query,
	)
	if err != nil {
		panic(err)
	}
	defer rows.Close()

	var result []*GMMail

	for rows.Next() {
		result = append(
			result,
			scanGMMailRows(rows),
		)
	}

	if err := rows.Err(); err != nil {
		panic(err)
	}

	return result
}

func (o gMMail) GetAll(
	ctx context.Context,
) []*GMMail {
	return o.getAll(
		ctx,
		txFromCtx(ctx),
	)
}

func (o gMMail) SelectAll(
	ctx context.Context,
) []*GMMail {
	return o.getAll(
		ctx,
		querierFromCtx(ctx),
	)
}

var ErrGMMailNotFound = errors.New(
	"user_gm_mail: row not found at update time",
)

func (o gMMail) Update(
	ctx context.Context,
	v *GMMail,
) error {
	tx := txFromCtx(ctx)

	if !v.loaded {
		return errors.New(
			"update GMMail must load first",
		)
	}

	if len(v.dirty) == 0 {
		return nil
	}

	var sets []string
	var args []any

	n := 0

	next := func() int {
		n++
		return n
	}

	if _, ok := v.dirty["params"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"params = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.params,
		)
	}

	if _, ok := v.dirty["award_list"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"award_list = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.awardList,
		)
	}

	if _, ok := v.dirty["start_at"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"start_at = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.startAt,
		)
	}

	if _, ok := v.dirty["end_at"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"end_at = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.endAt,
		)
	}

	if _, ok := v.dirty["channel"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"channel = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.channel,
		)
	}

	if _, ok := v.dirty["user_created_at"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"user_created_at = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.userCreatedAt,
		)
	}

	if _, ok := v.dirty["condition"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"condition = $%d",
				next(),
			),
		)

		args = append(
			args,
			v.condition,
		)
	}

	args = append(
		args,
		v.id,
	)

	query := fmt.Sprintf(
		"UPDATE user_gm_mail SET %s WHERE id = $%d",
		strings.Join(sets, ", "),
		n+1,
	)

	tag, err := tx.Exec(
		ctx,
		query,
		args...,
	)
	if err != nil {
		panic(err)
	}

	if tag.RowsAffected() == 0 {
		return ErrGMMailNotFound
	}

	v.origParams = v.params

	v.origAwardList = v.awardList

	v.origStartAt = v.startAt

	v.origEndAt = v.endAt

	v.origChannel = v.channel

	v.origUserCreatedAt = v.userCreatedAt

	v.origCondition = v.condition

	v.dirty = make(map[string]struct{})

	return nil
}

func (o gMMail) Insert(
	ctx context.Context,
	v *GMMail,
) {
	tx := txFromCtx(ctx)

	const query = "INSERT INTO user_gm_mail " +
		"(params, award_list, start_at, end_at, channel, user_created_at, condition) " +
		"VALUES ($1, $2, $3, $4, $5, $6, $7)" +
		" RETURNING id"

	row := tx.QueryRow(
		ctx,
		query,
		v.params,
		v.awardList,
		v.startAt,
		v.endAt,
		v.channel,
		v.userCreatedAt,
		v.condition,
	)

	if err := row.Scan(
		&v.id,
	); err != nil {
		panic(err)
	}

	v.loaded = true

	v.origParams = v.params

	v.origAwardList = v.awardList

	v.origStartAt = v.startAt

	v.origEndAt = v.endAt

	v.origChannel = v.channel

	v.origUserCreatedAt = v.userCreatedAt

	v.origCondition = v.condition

	v.dirty = make(map[string]struct{})
}
