// Code generated by pdbgen; DO NOT EDIT.

package ptable

import (
	"context"
	"errors"
	"fmt"
	"math/bits"
	"strconv"
	"strings"

	"pdbgen/dbctx"
)

var UserMailTable mail

type mail struct{}

const (
	dirtyMailUid       uint64 = 1 << 0
	dirtyMailConfId    uint64 = 1 << 1
	dirtyMailState     uint64 = 1 << 2
	dirtyMailReceiveAt uint64 = 1 << 3
	dirtyMailParams    uint64 = 1 << 4
	dirtyMailAwardList uint64 = 1 << 5
)

type Mail struct {
	id            int64
	uid           int64
	confId        int32
	state         int32
	receiveAt     int64
	params        string
	awardList     string
	loaded        bool
	origUid       int64
	origConfId    int32
	origState     int32
	origReceiveAt int64
	origParams    string
	origAwardList string
	dirty         uint64
}

func NewMail() *Mail {
	return &Mail{}
}

func loadedMail(
	id int64,
	uid int64,
	confId int32,
	state int32,
	receiveAt int64,
	params string,
	awardList string,
) *Mail {
	return &Mail{
		id:            id,
		uid:           uid,
		confId:        confId,
		state:         state,
		receiveAt:     receiveAt,
		params:        params,
		awardList:     awardList,
		loaded:        true,
		origUid:       uid,
		origConfId:    confId,
		origState:     state,
		origReceiveAt: receiveAt,
		origParams:    params,
		origAwardList: awardList,
	}
}

func (o *Mail) Id() int64 {
	return o.id
}
func (o *Mail) SetUid(v int64) {
	if o.uid == v {
		return
	}
	o.uid = v
	o.dirty |= dirtyMailUid
}

func (o *Mail) Uid() int64 {
	return o.uid
}
func (o *Mail) SetConfId(v int32) {
	if o.confId == v {
		return
	}
	o.confId = v
	o.dirty |= dirtyMailConfId
}

func (o *Mail) ConfId() int32 {
	return o.confId
}
func (o *Mail) SetState(v int32) {
	if o.state == v {
		return
	}
	o.state = v
	o.dirty |= dirtyMailState
}

func (o *Mail) State() int32 {
	return o.state
}
func (o *Mail) SetReceiveAt(v int64) {
	if o.receiveAt == v {
		return
	}
	o.receiveAt = v
	o.dirty |= dirtyMailReceiveAt
}

func (o *Mail) ReceiveAt() int64 {
	return o.receiveAt
}
func (o *Mail) SetParams(v string) {
	if o.params == v {
		return
	}
	o.params = v
	o.dirty |= dirtyMailParams
}

func (o *Mail) Params() string {
	return o.params
}
func (o *Mail) SetAwardList(v string) {
	if o.awardList == v {
		return
	}
	o.awardList = v
	o.dirty |= dirtyMailAwardList
}

func (o *Mail) AwardList() string {
	return o.awardList
}

func (o *Mail) ResetToLoaded() {
	o.uid = o.origUid
	o.confId = o.origConfId
	o.state = o.origState
	o.receiveAt = o.origReceiveAt
	o.params = o.origParams
	o.awardList = o.origAwardList
	o.dirty = 0
}

const selectColumnsMail = "id, uid, conf_id, state, receive_at, params, award_list"

func scanMail(s dbctx.Scanner) (*Mail, error) {
	var (
		id        int64
		uid       int64
		confId    int32
		state     int32
		receiveAt int64
		params    string
		awardList string
	)
	if err := s.Scan(
		&id,
		&uid,
		&confId,
		&state,
		&receiveAt,
		&params,
		&awardList,
	); err != nil {
		return nil, err
	}
	return loadedMail(
		id,
		uid,
		confId,
		state,
		receiveAt,
		params,
		awardList,
	), nil
}

func (o mail) getId(
	ctx context.Context,
	q dbctx.Querier,
	id int64,
) *Mail {
	const query = "SELECT " + selectColumnsMail +
		" FROM user_mail" +
		" WHERE id = $1"
	return dbctx.QueryOne(ctx, q, query, scanMail, id)
}

func (o mail) GetById(
	ctx context.Context,
	id int64,
) *Mail {
	return o.getId(
		ctx,
		dbctx.TxFromCtx(ctx),
		id,
	)
}

func (o mail) SelectById(
	ctx context.Context,
	id int64,
) *Mail {
	return o.getId(
		ctx,
		dbctx.QuerierFromCtx(ctx),
		id,
	)
}

func (o mail) listUidConfId(
	ctx context.Context,
	q dbctx.Querier,
	uid int64, confId int32,
) []*Mail {
	const query = "SELECT " + selectColumnsMail +
		" FROM user_mail" +
		" WHERE uid = $1 AND conf_id = $2"
	return dbctx.QueryList(ctx, q, query, scanMail, uid, confId)
}

func (o mail) ListByUidConfId(
	ctx context.Context,
	uid int64, confId int32,
) []*Mail {
	return o.listUidConfId(
		ctx,
		dbctx.TxFromCtx(ctx),
		uid, confId,
	)
}

func (o mail) SelectListByUidConfId(
	ctx context.Context,
	uid int64, confId int32,
) []*Mail {
	return o.listUidConfId(
		ctx,
		dbctx.QuerierFromCtx(ctx),
		uid, confId,
	)
}

func (o mail) getAll(
	ctx context.Context,
	q dbctx.Querier,
) []*Mail {
	const query = "SELECT " + selectColumnsMail +
		" FROM user_mail"
	return dbctx.QueryList(ctx, q, query, scanMail)
}

func (o mail) GetAll(
	ctx context.Context,
) []*Mail {
	return o.getAll(ctx, dbctx.TxFromCtx(ctx))
}

func (o mail) SelectAll(
	ctx context.Context,
) []*Mail {
	return o.getAll(ctx, dbctx.QuerierFromCtx(ctx))
}

var ErrMailNotFound = errors.New(
	"user_mail: row not found at update time",
)

// FlushStmt 实现 dbctx.Flusher。dirty == 0 时返回空 query，
// UnitOfWork 据此跳过这一行，不占用一次往返。
func (v *Mail) FlushStmt() (string, []any) {
	if !v.loaded || v.dirty == 0 {
		return "", nil
	}
	var sb strings.Builder
	args := make([]any, 0, bits.OnesCount64(v.dirty)+1)
	sb.WriteString("UPDATE user_mail SET ")
	if v.dirty&dirtyMailUid != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.uid)
		sb.WriteString("uid = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyMailConfId != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.confId)
		sb.WriteString("conf_id = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyMailState != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.state)
		sb.WriteString("state = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyMailReceiveAt != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.receiveAt)
		sb.WriteString("receive_at = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyMailParams != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.params)
		sb.WriteString("params = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyMailAwardList != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.awardList)
		sb.WriteString("award_list = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	args = append(args, v.id)
	sb.WriteString(" WHERE id = $")
	sb.WriteString(strconv.Itoa(len(args)))
	return sb.String(), args
}

// FlushDone 实现 dbctx.Flusher，在对应 UPDATE 执行成功后回调，
// 同步 orig 快照并清空 dirty；rows == 0 说明这一行已被删除或从未存在。
func (v *Mail) FlushDone(rows int64) error {
	if rows == 0 {
		return ErrMailNotFound
	}
	v.origUid = v.uid
	v.origConfId = v.confId
	v.origState = v.state
	v.origReceiveAt = v.receiveAt
	v.origParams = v.params
	v.origAwardList = v.awardList
	v.dirty = 0
	return nil
}

// Update 是不经过 UnitOfWork 的直接落库入口，
// 生成代码内部不再调用它，仅供业务代码需要立即写库时使用。
func (o mail) Update(
	ctx context.Context,
	v *Mail,
) error {
	query, args := v.FlushStmt()
	if query == "" {
		return nil
	}
	tag, err := dbctx.TxFromCtx(ctx).Exec(ctx, query, args...)
	if err != nil {
		return fmt.Errorf("user_mail update: %w", err)
	}
	return v.FlushDone(tag.RowsAffected())
}

func (o mail) Insert(
	ctx context.Context,
	v *Mail,
) {
	tx := dbctx.TxFromCtx(ctx)
	const query = "INSERT INTO user_mail " +
		"(uid, conf_id, state, receive_at, params, award_list) " +
		"VALUES ($1, $2, $3, $4, $5, $6)" +
		" RETURNING id"

	row := tx.QueryRow(
		ctx,
		query,
		v.uid,
		v.confId,
		v.state,
		v.receiveAt,
		v.params,
		v.awardList,
	)
	if err := row.Scan(
		&v.id,
	); err != nil {
		panic(err)
	}

	v.loaded = true

	v.origUid = v.uid

	v.origConfId = v.confId

	v.origState = v.state

	v.origReceiveAt = v.receiveAt

	v.origParams = v.params

	v.origAwardList = v.awardList

	v.dirty = 0
	dbctx.Track(ctx, v)
}
