// Code generated by pdbgen; DO NOT EDIT.

package ptable

import (
	"context"
	"errors"
	"fmt"
	"math/bits"
	"strconv"
	"strings"

	"pdbgen/dbctx"
)

var UserGmMailTable gMMail

type gMMail struct{}

const (
	dirtyGMMailParams        uint64 = 1 << 0
	dirtyGMMailAwardList     uint64 = 1 << 1
	dirtyGMMailStartAt       uint64 = 1 << 2
	dirtyGMMailEndAt         uint64 = 1 << 3
	dirtyGMMailChannel       uint64 = 1 << 4
	dirtyGMMailUserCreatedAt uint64 = 1 << 5
	dirtyGMMailCondition     uint64 = 1 << 6
)

type GMMail struct {
	id                int64
	params            string
	awardList         string
	startAt           int64
	endAt             int64
	channel           string
	userCreatedAt     int64
	condition         string
	loaded            bool
	origParams        string
	origAwardList     string
	origStartAt       int64
	origEndAt         int64
	origChannel       string
	origUserCreatedAt int64
	origCondition     string
	dirty             uint64
}

func NewGMMail() *GMMail {
	return &GMMail{}
}

func loadedGMMail(
	id int64,
	params string,
	awardList string,
	startAt int64,
	endAt int64,
	channel string,
	userCreatedAt int64,
	condition string,
) *GMMail {
	return &GMMail{
		id:                id,
		params:            params,
		awardList:         awardList,
		startAt:           startAt,
		endAt:             endAt,
		channel:           channel,
		userCreatedAt:     userCreatedAt,
		condition:         condition,
		loaded:            true,
		origParams:        params,
		origAwardList:     awardList,
		origStartAt:       startAt,
		origEndAt:         endAt,
		origChannel:       channel,
		origUserCreatedAt: userCreatedAt,
		origCondition:     condition,
	}
}

func (o *GMMail) Id() int64 {
	return o.id
}
func (o *GMMail) SetParams(v string) {
	if o.params == v {
		return
	}
	o.params = v
	o.dirty |= dirtyGMMailParams
}

func (o *GMMail) Params() string {
	return o.params
}
func (o *GMMail) SetAwardList(v string) {
	if o.awardList == v {
		return
	}
	o.awardList = v
	o.dirty |= dirtyGMMailAwardList
}

func (o *GMMail) AwardList() string {
	return o.awardList
}
func (o *GMMail) SetStartAt(v int64) {
	if o.startAt == v {
		return
	}
	o.startAt = v
	o.dirty |= dirtyGMMailStartAt
}

func (o *GMMail) StartAt() int64 {
	return o.startAt
}
func (o *GMMail) SetEndAt(v int64) {
	if o.endAt == v {
		return
	}
	o.endAt = v
	o.dirty |= dirtyGMMailEndAt
}

func (o *GMMail) EndAt() int64 {
	return o.endAt
}
func (o *GMMail) SetChannel(v string) {
	if o.channel == v {
		return
	}
	o.channel = v
	o.dirty |= dirtyGMMailChannel
}

func (o *GMMail) Channel() string {
	return o.channel
}
func (o *GMMail) SetUserCreatedAt(v int64) {
	if o.userCreatedAt == v {
		return
	}
	o.userCreatedAt = v
	o.dirty |= dirtyGMMailUserCreatedAt
}

func (o *GMMail) UserCreatedAt() int64 {
	return o.userCreatedAt
}
func (o *GMMail) SetCondition(v string) {
	if o.condition == v {
		return
	}
	o.condition = v
	o.dirty |= dirtyGMMailCondition
}

func (o *GMMail) Condition() string {
	return o.condition
}

func (o *GMMail) ResetToLoaded() {
	o.params = o.origParams
	o.awardList = o.origAwardList
	o.startAt = o.origStartAt
	o.endAt = o.origEndAt
	o.channel = o.origChannel
	o.userCreatedAt = o.origUserCreatedAt
	o.condition = o.origCondition
	o.dirty = 0
}

const selectColumnsGMMail = "id, params, award_list, start_at, end_at, channel, user_created_at, condition"

func scanGMMail(s dbctx.Scanner) (*GMMail, error) {
	var (
		id            int64
		params        string
		awardList     string
		startAt       int64
		endAt         int64
		channel       string
		userCreatedAt int64
		condition     string
	)
	if err := s.Scan(
		&id,
		&params,
		&awardList,
		&startAt,
		&endAt,
		&channel,
		&userCreatedAt,
		&condition,
	); err != nil {
		return nil, err
	}
	return loadedGMMail(
		id,
		params,
		awardList,
		startAt,
		endAt,
		channel,
		userCreatedAt,
		condition,
	), nil
}

func (o gMMail) getId(
	ctx context.Context,
	q dbctx.Querier,
	id int64,
) *GMMail {
	const query = "SELECT " + selectColumnsGMMail +
		" FROM user_gm_mail" +
		" WHERE id = $1"
	return dbctx.QueryOne(ctx, q, query, scanGMMail, id)
}

func (o gMMail) GetById(
	ctx context.Context,
	id int64,
) *GMMail {
	return o.getId(
		ctx,
		dbctx.TxFromCtx(ctx),
		id,
	)
}

func (o gMMail) SelectById(
	ctx context.Context,
	id int64,
) *GMMail {
	return o.getId(
		ctx,
		dbctx.QuerierFromCtx(ctx),
		id,
	)
}

func (o gMMail) getAll(
	ctx context.Context,
	q dbctx.Querier,
) []*GMMail {
	const query = "SELECT " + selectColumnsGMMail +
		" FROM user_gm_mail"
	return dbctx.QueryList(ctx, q, query, scanGMMail)
}

func (o gMMail) GetAll(
	ctx context.Context,
) []*GMMail {
	return o.getAll(ctx, dbctx.TxFromCtx(ctx))
}

func (o gMMail) SelectAll(
	ctx context.Context,
) []*GMMail {
	return o.getAll(ctx, dbctx.QuerierFromCtx(ctx))
}

var ErrGMMailNotFound = errors.New(
	"user_gm_mail: row not found at update time",
)

// FlushStmt 实现 dbctx.Flusher。dirty == 0 时返回空 query，
// UnitOfWork 据此跳过这一行，不占用一次往返。
func (v *GMMail) FlushStmt() (string, []any) {
	if !v.loaded || v.dirty == 0 {
		return "", nil
	}
	var sb strings.Builder
	args := make([]any, 0, bits.OnesCount64(v.dirty)+1)
	sb.WriteString("UPDATE user_gm_mail SET ")
	if v.dirty&dirtyGMMailParams != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.params)
		sb.WriteString("params = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyGMMailAwardList != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.awardList)
		sb.WriteString("award_list = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyGMMailStartAt != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.startAt)
		sb.WriteString("start_at = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyGMMailEndAt != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.endAt)
		sb.WriteString("end_at = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyGMMailChannel != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.channel)
		sb.WriteString("channel = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyGMMailUserCreatedAt != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.userCreatedAt)
		sb.WriteString("user_created_at = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	if v.dirty&dirtyGMMailCondition != 0 {
		if len(args) > 0 {
			sb.WriteString(", ")
		}
		args = append(args, v.condition)
		sb.WriteString("condition = $")
		sb.WriteString(strconv.Itoa(len(args)))
	}
	args = append(args, v.id)
	sb.WriteString(" WHERE id = $")
	sb.WriteString(strconv.Itoa(len(args)))
	return sb.String(), args
}

// FlushDone 实现 dbctx.Flusher，在对应 UPDATE 执行成功后回调，
// 同步 orig 快照并清空 dirty；rows == 0 说明这一行已被删除或从未存在。
func (v *GMMail) FlushDone(rows int64) error {
	if rows == 0 {
		return ErrGMMailNotFound
	}
	v.origParams = v.params
	v.origAwardList = v.awardList
	v.origStartAt = v.startAt
	v.origEndAt = v.endAt
	v.origChannel = v.channel
	v.origUserCreatedAt = v.userCreatedAt
	v.origCondition = v.condition
	v.dirty = 0
	return nil
}

// Update 是不经过 UnitOfWork 的直接落库入口，
// 生成代码内部不再调用它，仅供业务代码需要立即写库时使用。
func (o gMMail) Update(
	ctx context.Context,
	v *GMMail,
) error {
	query, args := v.FlushStmt()
	if query == "" {
		return nil
	}
	tag, err := dbctx.TxFromCtx(ctx).Exec(ctx, query, args...)
	if err != nil {
		return fmt.Errorf("user_gm_mail update: %w", err)
	}
	return v.FlushDone(tag.RowsAffected())
}

func (o gMMail) Insert(
	ctx context.Context,
	v *GMMail,
) {
	tx := dbctx.TxFromCtx(ctx)
	const query = "INSERT INTO user_gm_mail " +
		"(params, award_list, start_at, end_at, channel, user_created_at, condition) " +
		"VALUES ($1, $2, $3, $4, $5, $6, $7)" +
		" RETURNING id"

	row := tx.QueryRow(
		ctx,
		query,
		v.params,
		v.awardList,
		v.startAt,
		v.endAt,
		v.channel,
		v.userCreatedAt,
		v.condition,
	)
	if err := row.Scan(
		&v.id,
	); err != nil {
		panic(err)
	}

	v.loaded = true

	v.origParams = v.params

	v.origAwardList = v.awardList

	v.origStartAt = v.startAt

	v.origEndAt = v.endAt

	v.origChannel = v.channel

	v.origUserCreatedAt = v.userCreatedAt

	v.origCondition = v.condition

	v.dirty = 0
	dbctx.Track(ctx, v)
}
