// Code generated by pdbgen; DO NOT EDIT.

package ptable

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
)

var UserTable user

type user struct{}

type User struct {
	id          int64
	name        string
	lastLoginAt time.Time
	createdAt   time.Time
	token       string

	loaded          bool
	origName        string
	origLastLoginAt time.Time
	origCreatedAt   time.Time
	origToken       string

	dirty map[string]struct{}
}

func NewUser() *User {
	return &User{
		dirty: make(map[string]struct{}),
	}
}

func loadedUser(
	id int64,
	name string,
	lastLoginAt time.Time,
	createdAt time.Time,
	token string,
) *User {
	return &User{
		id:          id,
		name:        name,
		lastLoginAt: lastLoginAt,
		createdAt:   createdAt,
		token:       token,

		loaded:          true,
		origName:        name,
		origLastLoginAt: lastLoginAt,
		origCreatedAt:   createdAt,
		origToken:       token,

		dirty: make(map[string]struct{}),
	}
}

func (o *User) SetName(v string) {
	if o.name == v {
		return
	}

	o.name = v
	o.dirty["name"] = struct{}{}
}

func (o *User) Name() string {
	return o.name
}

func (o *User) SetLastLoginAt(v time.Time) {
	if o.lastLoginAt == v {
		return
	}

	o.lastLoginAt = v
	o.dirty["last_login_at"] = struct{}{}
}

func (o *User) LastLoginAt() time.Time {
	return o.lastLoginAt
}

func (o *User) SetCreatedAt(v time.Time) {
	if o.createdAt == v {
		return
	}

	o.createdAt = v
	o.dirty["created_at"] = struct{}{}
}

func (o *User) CreatedAt() time.Time {
	return o.createdAt
}

func (o *User) SetToken(v string) {
	if o.token == v {
		return
	}

	o.token = v
	o.dirty["token"] = struct{}{}
}

func (o *User) Token() string {
	return o.token
}

func (o *User) Id() int64 {
	return o.id
}

// ResetToLoaded restores every non-primary-key field to the last
// successfully loaded/inserted/updated snapshot.
func (o *User) ResetToLoaded() {
	o.name = o.origName
	o.lastLoginAt = o.origLastLoginAt
	o.createdAt = o.origCreatedAt
	o.token = o.origToken

	o.dirty = make(map[string]struct{})
}

const selectColumnsUser = "id, name, last_login_at, created_at, token"

func scanUser(row pgx.Row) *User {
	var (
		id          int64
		name        string
		lastLoginAt time.Time
		createdAt   time.Time
		token       string
	)

	if err := row.Scan(
		&id,
		&name,
		&lastLoginAt,
		&createdAt,
		&token,
	); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil
		}

		panic(err)
	}

	return loadedUser(
		id,
		name,
		lastLoginAt,
		createdAt,
		token,
	)
}

func (user) GetById(
	ctx context.Context,
	id int64,
) *User {
	tx := txFromCtx(ctx)

	const q = "SELECT " + selectColumnsUser +
		" FROM user" +
		" WHERE id = $1"

	row := tx.QueryRow(
		ctx,
		q,
		id,
	)

	return scanUser(row)
}

func (user) Update(
	ctx context.Context,
	o *User,
) error {
	tx := txFromCtx(ctx)

	if !o.loaded {
		return errors.New(
			"update User must load first",
		)
	}

	if len(o.dirty) == 0 {
		return nil
	}

	var sets []string
	var args []any

	n := 0

	next := func() int {
		n++
		return n
	}

	if _, ok := o.dirty["name"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"name = $%d",
				next(),
			),
		)

		args = append(
			args,
			o.name,
		)
	}

	if _, ok := o.dirty["last_login_at"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"last_login_at = $%d",
				next(),
			),
		)

		args = append(
			args,
			o.lastLoginAt,
		)
	}

	if _, ok := o.dirty["created_at"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"created_at = $%d",
				next(),
			),
		)

		args = append(
			args,
			o.createdAt,
		)
	}

	if _, ok := o.dirty["token"]; ok {
		sets = append(
			sets,
			fmt.Sprintf(
				"token = $%d",
				next(),
			),
		)

		args = append(
			args,
			o.token,
		)
	}

	args = append(args, o.id)

	q := fmt.Sprintf(
		"UPDATE user SET %s WHERE id = $%d",
		strings.Join(sets, ", "),
		n+1,
	)

	tag, err := tx.Exec(ctx, q, args...)
	if err != nil {
		panic(err)
	}

	if tag.RowsAffected() == 0 {
		return ErrUserNotFound
	}

	o.origName = o.name

	o.origLastLoginAt = o.lastLoginAt

	o.origCreatedAt = o.createdAt

	o.origToken = o.token

	o.dirty = make(map[string]struct{})

	return nil
}

var ErrUserNotFound = errors.New(
	"user: row not found at update time",
)

func (user) Insert(
	ctx context.Context,
	o *User,
) {
	tx := txFromCtx(ctx)

	const q = "INSERT INTO user " +
		"(name, last_login_at, created_at, token) " +
		"VALUES ($1, $2, $3, $4)" +
		" RETURNING id"

	row := tx.QueryRow(
		ctx,
		q,
		o.name,
		o.lastLoginAt,
		o.createdAt,
		o.token,
	)

	if err := row.Scan(&o.id); err != nil {
		panic(err)
	}

	o.loaded = true

	o.origName = o.name

	o.origLastLoginAt = o.lastLoginAt

	o.origCreatedAt = o.createdAt

	o.origToken = o.token

	o.dirty = make(map[string]struct{})
}
