package main

import (
	"flag"
	"fmt"
	"pdbgen/readxml"
	"strings"
)

func main() {
	schemaFile := flag.String(
		"schema",
		"./pdb.xml",
		"schema xml file",
	)

	outDir := flag.String(
		"out",
		"ptable",
		"ddl output directory, default: genOutput in xml",
	)

	flag.Parse()

	schema, err := readxml.LoadSchema(*schemaFile)
	if err != nil {
		panic(err)
	}

	if *outDir == "" {
		*outDir = schema.GenOutput
	}

	if *outDir == "" {
		*outDir = "./ddl/generated"
	}

	if err := generate(schema, *outDir); err != nil {
		panic(err)
	}
}

func generate(schema *readxml.Schema, outDir string) error {
	//if err := os.MkdirAll(outDir, 0755); err != nil {
	//	return err
	//}

	var b strings.Builder

	b.WriteString("-- Code generated by pdb ddl generator; DO NOT EDIT.\n\n")

	// schema 不存在时创建
	fmt.Fprintf(
		&b,
		"CREATE SCHEMA IF NOT EXISTS %s;\n\n",
		quoteIdent(schema.Schema),
	)

	for _, table := range schema.Tables {
		if err := generateTableDDL(
			&b,
			schema,
			table,
		); err != nil {
			return err
		}

		b.WriteString("\n\n")
	}
	//
	//output := filepath.Join(outDir, "schema.sql")
	//
	//if err := os.WriteFile(
	//	output,
	//	[]byte(b.String()),
	//	0644,
	//); err != nil {
	//	return err
	//}
	//
	//fmt.Println("generated", output)
	fmt.Println(b.String())

	return nil
}

func generateTableDDL(
	b *strings.Builder,
	schema *readxml.Schema,
	table readxml.Table,
) error {
	bean, err := readxml.FindBean(schema, table.Bean)
	if err != nil {
		return err
	}

	// CREATE TABLE
	fmt.Fprintf(
		b,
		"CREATE TABLE IF NOT EXISTS %s.%s (\n",
		quoteIdent(schema.Schema),
		quoteIdent(table.Name),
	)

	for i, v := range bean.Variables {
		columnType, defaultValue, err := sqlType(v.Type)
		if err != nil {
			return fmt.Errorf(
				"table %s column %s: %w",
				table.Name,
				v.Name,
				err,
			)
		}

		fmt.Fprintf(
			b,
			"\t%s %s NOT NULL DEFAULT %s",
			quoteIdent(readxml.SnakeCase(v.Name)),
			columnType,
			defaultValue,
		)

		if i != len(bean.Variables)-1 {
			b.WriteString(",")
		}

		b.WriteString("\n")
	}

	b.WriteString(");\n\n")

	// PRIMARY KEY / IDENTITY
	if table.PrimaryKey != nil {
		b.WriteString("ALTER TABLE ")
		b.WriteString(quoteIdent(schema.Schema))
		b.WriteString(".")
		b.WriteString(quoteIdent(table.Name))
		b.WriteString("\n")

		var actions []string

		if table.PrimaryKey.AutoIncrement {
			identity := fmt.Sprintf(
				"ALTER COLUMN %s ADD GENERATED ALWAYS AS IDENTITY",
				quoteIdent(
					readxml.SnakeCase(table.PrimaryKey.Variable),
				),
			)

			if table.PrimaryKey.Start != 0 {
				identity += fmt.Sprintf(
					" (START WITH %d)",
					table.PrimaryKey.Start,
				)
			}

			actions = append(actions, identity)
		}

		actions = append(
			actions,
			fmt.Sprintf(
				"ADD CONSTRAINT %s PRIMARY KEY (%s)",
				quoteIdent(table.PrimaryKey.Name),
				quoteIdent(
					readxml.SnakeCase(table.PrimaryKey.Variable),
				),
			),
		)

		b.WriteString("\t")
		b.WriteString(strings.Join(actions, ",\n\t"))
		b.WriteString(";\n\n")
	}

	// INDEX
	for _, index := range table.Indexes {
		if err := generateIndexDDL(
			b,
			schema,
			table,
			index,
		); err != nil {
			return err
		}

		b.WriteString("\n")
	}

	return nil
}

func generateIndexDDL(
	b *strings.Builder,
	schema *readxml.Schema,
	table readxml.Table,
	index readxml.Index,
) error {
	columns := readxml.SplitTrimSpace(index.Variable)

	if len(columns) == 0 {
		return fmt.Errorf(
			"table %s index %s has no columns",
			table.Name,
			index.Name,
		)
	}

	b.WriteString("CREATE ")

	if index.Unique {
		b.WriteString("UNIQUE ")
	}

	b.WriteString("INDEX IF NOT EXISTS ")
	b.WriteString(quoteIdent(index.Name))

	b.WriteString(" ON ")
	b.WriteString(quoteIdent(schema.Schema))
	b.WriteString(".")
	b.WriteString(quoteIdent(table.Name))
	b.WriteString(" (")

	for i, column := range columns {
		if i > 0 {
			b.WriteString(", ")
		}

		b.WriteString(
			quoteIdent(readxml.SnakeCase(column)),
		)
	}

	b.WriteString(");\n")

	return nil
}

func sqlType(goType string) (
	columnType string,
	defaultValue string,
	err error,
) {
	switch goType {
	case "int64":
		return "BIGINT", "0", nil

	case "int32":
		return "INTEGER", "0", nil

	case "int16":
		return "SMALLINT", "0", nil

	case "int8":
		return "SMALLINT", "0", nil

	case "string":
		return "TEXT", "''", nil

	default:
		return "", "", fmt.Errorf(
			"unsupported Go type %q",
			goType,
		)
	}
}

func quoteIdent(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
}
